import { BookTemplate, Home, Settings, Trash2Icon } from "lucide-react";
import { Theme } from "./types";

export const data = {
  user: {
    name: "Shadcnm",
    email: "m@example.com",
    avatar: "/avatars/shadcn.jpg",
  },
  navMain: [
    {
      title: "Home",
      url: "/dashboard",
      icon: Home,
    },
    {
      title: "Templates",
      url: "/templates",
      icon: BookTemplate,
    },
    {
      title: "Trash",
      url: "/trash",
      icon: Trash2Icon,
    },
    {
      title: "Settings",
      url: "/settings",
      icon: Settings,
    },
  ],
};

export const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.1,
    },
  },
};

export const itemVariants = {
  hidden: { y: 20, opacity: 0 },
  visible: {
    y: 0,
    opacity: 1,
    transition: {
      type: "spring",
      stiffness: 100,
    },
  },
};

export const themes: Theme[] = [
  {
    name: "Default",
    fontFamily: "'Inter','sans-serif'",
    fontColor: "#000000",
    backgroundColor: "#f0f0f0",
    slideBackgroundColor: "#ffffff",
    accentColor: "#3d82f6",
    navbarColor: "#ffffff",
    sidebarColor: "#f0f0f0",
    type: "light",
  },
  {
    name: "Midnight",
    fontFamily: "'Roboto', 'sans-serif'",
    fontColor: "#ffffff",
    backgroundColor: "#0f172a",
    slideBackgroundColor: "#1e293b",
    accentColor: "#60a5fa",
    navbarColor: "#0f172a",
    sidebarColor: "#1e293b",
    type: "dark",
  },
  {
    name: "Forest",
    fontFamily: "'Poppins', 'sans-serif'",
    fontColor: "#ffffff",
    backgroundColor: "#064e3b",
    slideBackgroundColor: "#065f46",
    accentColor: "#34d399",
    navbarColor: "#064e3b",
    sidebarColor: "#065f46",
    type: "dark",
  },
  {
    name: "Sunset",
    fontFamily: "'Montserrat', 'sans-serif'",
    fontColor: "#1a1a1a",
    backgroundColor: "#fff7ed",
    slideBackgroundColor: "#ffedd5",
    accentColor: "#f97316",
    navbarColor: "#fff7ed",
    sidebarColor: "#ffedd5",
    type: "light",
  },
  {
    name: "Ocean",
    fontFamily: "'Lato', 'sans-serif'",
    fontColor: "#ffffff",
    backgroundColor: "#0c4a6e",
    slideBackgroundColor: "#0369a1",
    accentColor: "#38bdf8",
    navbarColor: "#0c4a6e",
    sidebarColor: "#0369a1",
    type: "dark",
  },
  {
    name: "Lavender",
    fontFamily: "'Quicksand', 'sans-serif'",
    fontColor: "#1a1a1a",
    backgroundColor: "#f5f3ff",
    slideBackgroundColor: "#ede9fe",
    accentColor: "#8b5cf6",
    navbarColor: "#f5f3ff",
    sidebarColor: "#ede9fe",
    type: "light",
  },
  {
    name: "Cherry",
    fontFamily: "'Source Sans Pro', 'sans-serif'",
    fontColor: "#ffffff",
    backgroundColor: "#831843",
    slideBackgroundColor: "#9d174d",
    accentColor: "#fb7185",
    navbarColor: "#831843",
    sidebarColor: "#9d174d",
    type: "dark",
  },
  {
    name: "Mint",
    fontFamily: "'Nunito', 'sans-serif'",
    fontColor: "#1a1a1a",
    backgroundColor: "#ecfdf5",
    slideBackgroundColor: "#d1fae5",
    accentColor: "#10b981",
    navbarColor: "#ecfdf5",
    sidebarColor: "#d1fae5",
    type: "light",
  },
  {
    name: "Coffee",
    fontFamily: "'Merriweather', 'serif'",
    fontColor: "#ffffff",
    backgroundColor: "#44403c",
    slideBackgroundColor: "#57534e",
    accentColor: "#d6d3d1",
    navbarColor: "#44403c",
    sidebarColor: "#57534e",
    type: "dark",
  },
  {
    name: "Sky",
    fontFamily: "'Open Sans', 'sans-serif'",
    fontColor: "#1a1a1a",
    backgroundColor: "#e0f2fe",
    slideBackgroundColor: "#bae6fd",
    accentColor: "#0284c7",
    navbarColor: "#e0f2fe",
    sidebarColor: "#bae6fd",
    type: "light",
  },
  {
    name: "Ruby",
    fontFamily: "'Playfair Display', 'serif'",
    fontColor: "#ffffff",
    backgroundColor: "#881337",
    slideBackgroundColor: "#9f1239",
    accentColor: "#fda4af",
    navbarColor: "#881337",
    sidebarColor: "#9f1239",
    type: "dark",
  },
  {
    name: "Emerald",
    fontFamily: "'Ubuntu', 'sans-serif'",
    fontColor: "#1a1a1a",
    backgroundColor: "#ecfdf5",
    slideBackgroundColor: "#d1fae5",
    accentColor: "#059669",
    navbarColor: "#ecfdf5",
    sidebarColor: "#d1fae5",
    type: "light",
  },
  {
    name: "Cosmic",
    fontFamily: "'Space Grotesk', 'sans-serif'",
    fontColor: "#ffffff",
    backgroundColor: "#2e1065",
    slideBackgroundColor: "#4c1d95",
    accentColor: "#c4b5fd",
    navbarColor: "#2e1065",
    sidebarColor: "#4c1d95",
    type: "dark",
  },
  {
    name: "Coral",
    fontFamily: "'DM Sans', 'sans-serif'",
    fontColor: "#1a1a1a",
    backgroundColor: "#fff1f2",
    slideBackgroundColor: "#ffe4e6",
    accentColor: "#f43f5e",
    navbarColor: "#fff1f2",
    sidebarColor: "#ffe4e6",
    type: "light",
  },
  {
    name: "Nordic",
    fontFamily: "'IBM Plex Sans', 'sans-serif'",
    fontColor: "#ffffff",
    backgroundColor: "#1e3a8a",
    slideBackgroundColor: "#1e40af",
    accentColor: "#93c5fd",
    navbarColor: "#1e3a8a",
    sidebarColor: "#1e40af",
    type: "dark",
  },
];

export const CreatePageCard = [
  {
    title: "Use a",
    highlightedText: "Template",
    description: "Write a prompt and leave everything else for us to handle",
    type: "template",
  },
  {
    title: "Generate with",
    highlightedText: "Creative AI",
    description: "Write a prompt and leave everything else for us to handle",
    type: "creative-ai",
    highlight: true,
  },
  {
    title: "Start from",
    highlightedText: "Scratch",
    description: "Write a prompt and leave everything else for us to handle",
    type: "create-scratch",
  },
];
